application: hnarchive42
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: lxml
  version: "2.3"
- name: webapp2
  version: "2.5.2"

handlers:
- url: /task/crawl
  script: app.app
  login: admin

